#!/bin/sh -fu

export HOME="$AUTOPKGTEST_TMP"
export LIBGL_ALWAYS_SOFTWARE=1
export EGL_LOG_LEVEL=debug

# display glxinfo

xvfb-run --server-args="-screen 0 1024x768x24 -ac +extension GLX +render -noreset" glxinfo

# run the full pyOpenGL test suite

cp -r tests "$AUTOPKGTEST_TMP"

rv=0
for py in $(py3versions -r 2>/dev/null)
do cd "$AUTOPKGTEST_TMP"
   echo "Testing with $py:"
   xvfb-run --server-args="-screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp" $py -m pytest -v tests -k 'not test_test_glgetfloat_leak'
   rv=$(expr $rv + $?)
done
exit $rv
